### PR TITLE
fix(uipath-maestro-flow): name the warnings that are build failures

### PR DESCRIPTION
**Pull request by rockymadden**
## What

`greenfield.md` T3 already said a passing exit code with warnings is not done, but named only the connector-keyword warning as an example. So a flow shipped `Valid` with eleven warnings, two of which stated in plain words that both inline agents would run without the flow's inputs:

```
Agent "Dispute Analyst Agent" declares no inputs in its agent.json `inputSchema`,
but the flow node binds 4 inputs ("normalizedInvoice", "crmRecords", "erpRecords",
"discrepancySummary") under `inputs.agentInputVariables`. Because the agent.json
`inputSchema` declares no inputs, at runtime these bindings are silently dropped
— the agent runs without the flow's inputs.
```

Exit code 0, `Status: "Valid"`. The run then faulted. This was the `skill-flow-devcon-billing-dispute-resolution` coder-eval failure.

The validator's diagnosis was exact and named the four missing keys. Nothing in the skill said to stop on it.

## Changes

Replace the single connector example with the three warning classes that each describe a run that faults or silently does the wrong thing:

| Warning | At debug time |
|---|---|
| connector keyword on generic `core.action.http.v2` | runs against an undefined endpoint |
| `agentInputVariables` vs empty `inputSchema` | the agent never receives the flow's data, nothing faults, and with an empty `outputSchema` the fields downstream nodes read come back `undefined` |
| `not valid JavaScript` / `[EXPRESSION_DIAGNOSTIC] Cannot find name` | expression throws or evaluates to garbage |

Each row carries how to resolve it. The agent-input row links to the wiring section that owns the three-piece contract.

Two notes on scope:

- The consequence column states what the dropped bindings **guarantee**. An earlier revision said the agent "returns boilerplate" and that "every downstream read is `undefined`", which describes only the trace this came from, where the sidecar prompts were also empty and `outputSchema` was the bare `{content}`. With real prompts and a typed schema the agent still emits its declared fields, ungrounded rather than undefined.
- The third row deliberately excludes the `[EXPRESSION_DIAGNOSTIC] Property '<x>' does not exist on type` variant, which is frequently a registry schema-completeness artifact. `failure-modes.md:336` already covers that one.

The third class was also live in the same failing flow, unresolved: `erpLookup1.inputs.detail.filterVariables` carried `Unexpected token (1:62)` and `Cannot find name 'MCS'`.

## Verification

Reproduced on CLI 1.203.0: `flow validate` returns exit 0 and `Result: "Success"` with the agent-input warning present. Scoped to `greenfield.md` so it does not conflict with #3349.

## Checks

`check-links` 983/0, `check-link-text` 634/0, `check-depth` clean. `check-anchors` adds one anchor, resolves. The 1 bad anchor is the same pre-existing one as `main`.

## Related

- #3349, the inline-agent authoring order that produces this state
- #3350, the missing Switch `default` that turned it into a fault

## This mitigation has a hole

The `agentInputVariables` warning fires **only when `inputSchema` is empty**. Verified on 1.203.0: a node whose prompts reference none of its correctly-declared bindings still gets pruned at runtime and draws no diagnostic at all. So reading warnings harder cannot close that variant, and the CLI should either promote this warning to an error (it has no benign case) or extend it to cover the prune condition. Tracked separately, along with the offline assertion that does catch both.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: skills/uipath-maestro-flow/references/author/greenfield.md [hunk 1]
```diff
@@ -347,7 +347,15 @@ uip maestro flow node configure "<ProjectName>.flow" "<httpNodeId>" --detail '<D
...
+>
+> | Warning | What it means at debug time | Resolve by |
+> | --- | --- | --- |
+> | `mentions the "<connector>" connector keyword but uses the generic Managed HTTP type core.action.http.v2 with no connection binding` | The flow took the brand-name shortcut and runs against an undefined endpoint | Switch to the connector node (see [SKILL.md rule #3](../../SKILL.md#critical-rules-universal) and the anti-pattern list) |
+> | `declares no inputs in its agent.json \`inputSchema\`, but the flow node binds N inputs … these bindings are silently dropped` | The inline agent never receives the flow's data, so its output is unrelated to the run. Nothing faults, and with an empty `outputSchema` the fields downstream nodes read come back `undefined` | Add the keys to `inputSchema.properties`, then `uip agent refresh --inline-in-flow` — the warning names them ([inline-agent/impl.md § Wiring Flow Variables into Agent Prompts](plugins/inline-agent/impl.md#wiring-flow-variables-into-agent-prompts)) |
```
[the remark this answers is not in the document]
Comment (rockymadden) [reply skills/uipath-maestro-flow/references/author/greenfield.md]: Fixed in 5dca94daf.

The row now requires the `{{input.<key>}}` reference in `messages[].content` alongside the `inputSchema` key, says why `refresh` cannot supply it (it regenerates `contentTokens` from `content`, nothing more), and ends with `uip agent refresh --inline-in-flow` then `uip agent validate --inline-in-flow`.

Delivery needs no instruction here — the node binding is what makes this warning fire.

**Review by nikhil-maryala — APPROVED** [review]
## Overall decision: **Approve** ✅
**Severity tally — 0 Blocker · 0 Critical · 0 Major · 0 Minor · 0 Nit.** No inline findings.

Good change — promoting the single connector-keyword callout to a 3-row table of warnings-that-are-really-build-failures. Verified links resolve and the `plugins/inline-agent/impl.md#wiring-flow-variables-into-agent-prompts` anchor exists (heading present). The inline-agent row is cross-consistent with #3349: add the named keys to `inputSchema.properties` **and** read each as `{{input.<key>}}` in `messages[].content`, because a key no prompt token reads never reaches the model and `refresh` won't add the reference. Approving.
