### PR TITLE
feat(uipath-maestro-case): generate the bindings sidecar with the CLI, close the plain-Valid exit, and grade the strict SDD audit

### PR DESCRIPTION
**Pull request by roberts-cliff**
## Summary

Companion to UiPath/cli#4106 and UiPath/cli#4152, both merged: the strict / SDD validation profile, `bindings sync`, `format`, and the default-profile checks they added. Squashed to one commit on today's `main`.

**Sidecar.** `bindings_v2.json` is generated by `uip maestro case bindings sync`, never hand-written; Check 7 gates on `validate --strict`. `caseplan.json` is written pretty-printed and `uip maestro case format` runs after every write so Edit can patch it — every observed `perl`/`sed`/`node` in-place edit started from a compact file.

**Validation contract.** Strict at the Phase 3 exit and in Phase 4, plain at section ends; the strict validate runs alone, never chained. The repair loop continues while the strict `--sdd` error count falls and halts after two flat rounds or twelve (the three-retry cap stopped every build that needed more than three fixes). Step 12 maps every default- and strict-profile code the CLI emits to its Check, including this week's promotions and additions (`OUTPUT_ID_DUPLICATE`, `CONDITION_EXPR_HOISTED`, `SLA_ID_DUPLICATE`, `CONNECTOR_RESOURCE_KEY_MISMATCH`, `INPUT_BODY_ON_PLAIN_TASK`, `OUTPUT_VAR_ID_CASE_MISMATCH`, `SDD_LITERAL_MISMATCH`). The plain envelope's `Suppressed` block is the reason a plain `Valid` cannot close a build.

**Write-site rules from the golden rounds.** `rule-type:` is the JSON key `rule`; carry the SDD row's Display Name onto conditions; connector inputs are the spec envelope with fields under `body` in exactly the containers the cached spec populates; `metadata.` exposes four runtime fields; `bindings[]` entries and their `=bindings.` references are written together; a connector rule's context `resourceKey` is the key the `connection` entry resolves to.

**Golden task** (`tests/tasks/uipath-maestro-case/golden_rebuild/cm_golden_expense`): grades `validate --strict --sdd` exit 0 (weight 3 — a retreat to the plain profile is a scored miss), in-place script edits of `caseplan.json`, and `debug`/`publish` only at command position (`--help` probes exempt).

## Evidence

**CI, case suite on `gpt-5.6-luna`** — `cli_version=1.203.0-dev.8614` (`@uipath/cli` exact; tools at `@dev`, which resolved `maestro-tool` to `1.203.0-dev.8618`, the cli#4106 merge): **50/63**, three shards at -j 4 ([A](https://github.com/UiPath/skills/actions/runs/34510099349) 18/22 · [B](https://github.com/UiPath/skills/actions/runs/34510112043) 18/23 · [C](https://github.com/UiPath/skills/actions/runs/34510125152) 14/18).

- **`skill-case-golden-rebuild-cm-expense`: 1.0 on luna in CI**, first attempt. Before this branch the task had never passed locally on luna.
- Of the 13 failures: 3 were a grader `ImportError` broken on `main` too (fixed by #3207, now rebased in), 1 debug 504, 1 planner-owned design task, 1 e2e outcome probe, 7 luna misses on SDD intent (two of which exposed validator follow-ups, below).
- A/B baseline — the same three shards on `main`, same pin — is running: [A](https://github.com/UiPath/skills/actions/runs/34515895202) · [B](https://github.com/UiPath/skills/actions/runs/34515908182) · [C](https://github.com/UiPath/skills/actions/runs/34515921274). Result will be posted as a comment.

**Local luna rounds of 3 on the golden**, pass = every criterion at 1.0, rounds 34–42 on successive CLI builds: 3/3, 1/3, 0/3, 1/3, 0/3, 1/3, 1/3, 1/3, 1/3 — seventeen passes; the task had zero before round 21. Across every failed repeat in rounds 34–42, each grader miss was either named by the validator first or the agent never ran strict; the remaining exits are model behaviour (retreat to plain, skip strict, honest stop). `claude-sonnet-5` passes the golden 3/3 nightly on `main`.

**False-positive gate**: the 26 case plans that scored 1.0 in nightly `2026-09-09_04-18-27` produce zero error-level findings on the plain profile on every CLI build above; seventeen grader-passing golden artifacts stay at zero errors on plain, `--strict` and `--sdd`. This gate vetoed one severity promotion (var/id mismatch, since deleted in cli#4152) and shaped three rules.

## Stable failures (both refs, independent dispatches)

The A/B against `main` (comment below) flipped fourteen tasks at n=1 — noise. Four tasks failed on **both** refs, and two of them are fixture-SDD tasks where the SDD audit has independent authorship and can see a design miss, yet returns zero findings:

- `sla-from-sdd` — the SDD declares a conditional stage SLA (`=js:(vars.claimValue > 5000)`, 4 h) plus a default; both builds kept only the `=js:true` default. `--strict --sdd` reports nothing.
- `io-binding-matrix` — an explicit `->` reassignment minted as a bare output, no `originalVar`; the converter reads that field. `--strict --sdd` reports nothing.

These are the two CLI follow-ups (validator rules, corpus-first, fixture-SDD plans lead the measurement). The other two both-fails are `e2e-outcome-external` (outcome probe found no email / Jira record — environmental) and `edit-bound-task-add-remove` (agent skipped `solution resources remove`).

## Follow-ups (not in this PR)

- CLI: the two stable failures above — a `--sdd` check for declared conditional SLA rows, and `originalVar` required on non-custom task outputs with `source`/`target` and `id != var`.
- Product: MST-13582 (Case Manager agent) is a skill feature gap, untouched here.

### CODE REVIEW

**Comment by roberts-cliff** [comment]
## CI round 1 — case suite on `gpt-5.6-luna`, `cli_version=1.203.0-dev.8614` (tools at `@dev` → maestro-tool `1.203.0-dev.8618`)

Three shards, 63 tasks (two `windows`-tagged skipped): **50/63 pass**.

| Shard | Result | Run |
|---|---|---|
| A multi_stages_tasks / hitl / connector_features / entry_points_io | 18/22 | https://github.com/UiPath/skills/actions/runs/34510099349 |
| B sla_response / single_node / edit / diagnose | 18/23 | https://github.com/UiPath/skills/actions/runs/34510112043 |
| C twenty single-task folders (golden, both e2e) | 14/18 | https://github.com/UiPath/skills/actions/runs/34510125152 |

**`skill-case-golden-rebuild-cm-expense`: SUCCESS 1.0 on luna** — the task this branch was built for, passing in CI on the weak author.

The 13 failures, by cause:

- **3 grader crashes, not agent failures** — `sla-at-risk-enter-stage`, `sla-case-breach-oversight`, `sla-case-breach-takeover`: `ImportError: cannot import name 'is_non_required' from '_shared.sla_response_check'`. Broken on `main` too; fixed by #3207 (merged after this branch's rebase). Rebase picks it up.
- **1 infra** — `multi-linear-three-stages`: `case debug` hit a 504 Gateway Timeout polling element-executions.
- **1 planner-owned** — `phase-0-procurement-sla-interrupts` (design task, not this skill).
- **1 outcome probe** — `e2e-outcome-external`: no email / Jira issue found for the run reference after 27 min.
- **7 agent misses** on luna: fan-in join declared one entry condition instead of two; multi-sla put the caseIdentifier rule before the priority rule; sla-from-sdd flattened the conditional override into `=js:true`; io-binding left `originalVar` off a reassigned output; entry-points-io paraphrased the verbatim job-attachment constant; edit-bound-task-add-remove skipped `solution resources remove`; single-api-workflow failed its debug.

No luna baseline exists on `main` (nightly runs Sonnet), so the 7 misses are not yet attributable to the branch or to the model. Next round after rebasing onto #3207.

**Comment by roberts-cliff** [comment]
## A/B — same three shards on `main` vs this branch, same pin (`cli` 1.203.0-dev.8614 + tools at `@dev`), `gpt-5.6-luna`, one replicate per task

**Branch 50/63 · main 54/63.** Main runs: [A](https://github.com/UiPath/skills/actions/runs/34515895202) 21/22 · [B](https://github.com/UiPath/skills/actions/runs/34515908182) 21/23 · [C](https://github.com/UiPath/skills/actions/runs/34515921274) 12/18.

Fourteen tasks flipped; forty-nine agreed (45 both pass, 4 both fail: `e2e-outcome-external`, `edit-bound-task-add-remove`, `io-binding-matrix`, `sla-from-sdd`).

| task | branch | main |
|---|---|---|
| **golden-rebuild-cm-expense** | **1.0** | 0.33 |
| athena-cm-event | 1.0 | 0.83 |
| edit-add-task-run-once-default | 1.0 | 0.64 |
| multi-parallel-after-predecessor | 1.0 | 0.23 |
| registry-handoff-action-case-sdd-only | 1.0 | 0.62 |
| entry-points-io | 0.67 | 1.0 |
| multi-fan-in-join | 0.38 | 1.0 |
| multi-sla-with-escalation | 0.38 | 1.0 |
| single-api-workflow | 0.38 | 1.0 |
| multi-linear-three-stages | 0.5 (debug 504) | 1.0 |
| phase-0-procurement-sla-interrupts | 0.36 (planner-owned) | 1.0 |
| sla-at-risk-enter-stage | 0.5 (grader crash, #3207) | 1.0 |
| sla-case-breach-oversight | 0.5 (grader crash, #3207) | 1.0 |
| sla-case-breach-takeover | 0.5 (grader crash, #3207) | 1.0 |

Remove the three grader crashes (fixed on `main` between the two dispatches, now rebased in), the 504 and the planner-owned task, and it is **branch +5 / main +4 on tasks that graded the skill** — inside the noise floor this model shows on the golden alone (0/3 to 3/3 between identical CLI builds). The golden itself flipped to the branch.

Caveats, all three real:
1. **Same CLI in both arms**, so this isolates the skill's instructions, not the validator rules. `main` never invokes `--strict --sdd`; the branch is the only arm that pays for strict findings, so "longer loop" and "strict findings cost" are entangled by design. The rules question needs the same skill ref against old vs new CLI, several replicates.
2. **Tool drift between arms**: the branch arm installed `maestro-tool` 8618/8619, the main arm (55 min later) every tool at 8620 — a test-only diff on the merge, same validator behaviour, but not identical builds.
3. **n = 1 per task.** Transcript check on `multi-fan-in-join`: the branch repeat ran 19 commands, both strict audits Valid, no finding repaired — it chose one AND entry condition holding both upstream rules where the grader wants two conditions. A design call, not a finding.

Ad-hoc dashboard runs of the same pair are queued on the nightly pipeline (builds 13342516 branch / 13342517 main) for a second replicate.

**Review by Yiqi517 — APPROVED** [review]
Got it!

**Review by StephenHanzlik — APPROVED** [review]

**Review by charlesliu9 — APPROVED** [review]

**Comment by roberts-cliff** [comment]
## Dashboard pair (nightly pipeline, ad-hoc) — `gpt-5.6-terra`, codex, all tools at `1.203.0-dev.8620` in both arms

Same case filter, same harness, same tool build in both arms (no drift this time), one replicate per task, 65 tasks each.

| ref | result | run |
|---|---|---|
| this branch (pre-merge head) | **62/65** | evalboard `adhoc-2026-09-10_20-49-33` · [build 13343102](https://uipath.visualstudio.com/coder_eval/_build/results?buildId=13343102&view=results) |
| `main` (pre-merge) | **56/65** | evalboard `adhoc-2026-09-10_20-50-56` · [build 13343103](https://uipath.visualstudio.com/coder_eval/_build/results?buildId=13343103&view=results) |

Both fail: `golden-rebuild-cm-expense` (0.27 / 0.24 — terra has never passed the golden; it fails it in ~3 min on every build), `io-binding-matrix` (0.33 / 0.33 — the `originalVar` stable failure, cli#4160). Branch-only fail: `phase-0-case-reasoning-regressions` (planner-owned). Main-only fails: `aged-invoice-structural`, `athena-cm-event`, `e2e-expense-runnable`, `e2e-outcome-external`, `logging-issue-log`, `multi-sla-with-escalation`, `single-case-management`.

Same caveats as the GitHub A/B — same CLI in both arms so this measures the skill's instructions, n = 1 — but with build parity. On terra the branch is +7 / −1 against main; on luna (GitHub pair, drifted tool builds) it was a wash. Neither model passes the golden at one replicate here; luna did in the GitHub run.
